/**
 * Input schema for the adminManageCoupon callable.
 *
 * PURE: zod + zodHelpers only, no firebase imports — so it is unit-testable and
 * can be shared by the wrapper without dragging in module-scope admin.firestore()
 * side effects. All callable input schemas should live under src/schemas/ for
 * this reason. (Do NOT put them in src/shared/ — that directory is generated by
 * scripts/copy-shared.mjs and will be overwritten.)
 */

import { z } from "zod";
import { nullish } from "../lib/zodHelpers";

const couponId = z.string().trim().min(1).max(200);

/**
 * Coupon body for op:"create". Strict — an unknown field is rejected rather than
 * spread into the coupons doc. usageLog is the reservation ledger (ADR-0002), so
 * a caller may only seed it empty; createdAt is re-derived server-side.
 */
export const couponCreateBody = z.strictObject({
    code: z.string().trim().min(1).max(64),
    discountType: z.enum(["percentage", "flat"]),
    discountValue: z.number().finite().nonnegative(),
    isActive: z.boolean(),
    usesCount: z.number().int().nonnegative(),
    createdAt: z.number().int().nonnegative(),
    usageLog: z.array(z.unknown()).max(0).optional(),
    maxUses: nullish(z.number().int().positive()),
    perUserLimit: nullish(z.number().int().positive()),
    expiresAt: nullish(z.number().int().nonnegative()),
    allowedPoolTypes: nullish(z.array(z.string().min(1)).min(1)),
});

/** Multi-shape callable — discriminated on `op` (sweep C1). */
export const adminManageCouponSchema = z.discriminatedUnion("op", [
    z.strictObject({ op: z.literal("create"), data: couponCreateBody }),
    z.strictObject({ op: z.literal("delete"), couponId }),
    z.strictObject({ op: z.literal("toggle"), couponId, data: z.strictObject({ isActive: z.boolean() }) }),
]);

export type AdminManageCouponInput = z.infer<typeof adminManageCouponSchema>;
