/**
 * Input schemas for the remaining adminBillingOps callables (companion to
 * schemas/adminManageCoupon.ts): adminSaveBillingConfig, adminUpdatePoolBilling,
 * adminAdjustUserCredits.
 *
 * PURE: zod only, no firebase imports — unit-testable and safe to share with the
 * validated() wrapper. (Do NOT move to src/shared/ — that dir is generated by
 * scripts/copy-shared.mjs and overwritten. Importing FROM shared is fine: those
 * modules are pure zod too.)
 */

import { z } from "zod";
import { BillingConfigSchema } from "../shared/schemas/billingConfig";

const poolId = z.string().trim().min(1).max(200);
const targetUid = z.string().trim().min(1).max(200);

/**
 * adminSaveBillingConfig — discriminated on `kind` (sweep C1).
 * - billing: config is fully modeled; parse it here so the handler persists the
 *   canonical BillingConfig (defaults materialized, unknown keys stripped),
 *   matching the pre-wrapper safeParse-then-persist behavior.
 * - referral: unmodeled passthrough object (behavior preserved).
 */
export const adminSaveBillingConfigSchema = z.discriminatedUnion("kind", [
    z.strictObject({ kind: z.literal("billing"), config: BillingConfigSchema }),
    z.strictObject({ kind: z.literal("referral"), config: z.record(z.string(), z.unknown()) }),
]);

/**
 * adminUpdatePoolBilling — discriminated on `action` (sweep C1).
 * - override: requires a billing-override object (old code threw without it).
 * - extendTrial: no payload.
 * - resetGrace: optional { gracePeriodDays }; handler defaults to 7 when absent.
 */
export const adminUpdatePoolBillingSchema = z.discriminatedUnion("action", [
    z.strictObject({ poolId, action: z.literal("override"), data: z.record(z.string(), z.unknown()) }),
    z.strictObject({ poolId, action: z.literal("extendTrial") }),
    z.strictObject({
        poolId,
        action: z.literal("resetGrace"),
        data: z.strictObject({ gracePeriodDays: z.number().finite().nonnegative() }).optional(),
    }),
]);

/**
 * adminAdjustUserCredits — single shape. At least one numeric credit field is
 * required; the MAX_CREDITS_PER_BUNDLE cap and floor stay in the handler
 * (business rule with a specific message), not the shape gate.
 */
export const adminAdjustUserCreditsSchema = z
    .strictObject({
        targetUid,
        referralCredits: z.number().finite().optional(),
        freePoolsAvailable: z.number().finite().optional(),
    })
    .refine(
        (d) => typeof d.referralCredits === "number" || typeof d.freePoolsAvailable === "number",
        { message: "at least one numeric credit field is required." },
    );

export type AdminSaveBillingConfigInput = z.infer<typeof adminSaveBillingConfigSchema>;
export type AdminUpdatePoolBillingInput = z.infer<typeof adminUpdatePoolBillingSchema>;
export type AdminAdjustUserCreditsInput = z.infer<typeof adminAdjustUserCreditsSchema>;
