// Member-voiced mirrors of the CONTEXT.md glossary — K1, PLAN-HELP-SYSTEM §3 D4.
//
// CONTEXT.md stays the source of truth for MEANING. It is written for
// engineers ("Stored as a uid in the SERVER-OWNED `pools/{id}.coManagers`
// array"), so shipping it verbatim would be the wrong copy for the reader.
// Instead each term is mirrored here in the reader's voice
// (`docs/help-voice.md`) and NAMES the CONTEXT.md heading it mirrors, and
// `tests/help-glossary-invariants.test.ts` fails when:
//
//   1. a CONTEXT.md `### ` heading has no mirror and no allowlist row,
//   2. a mirror names a heading that no longer exists,
//   3. a mirror's copy breaks the voice rules.
//
// So CONTEXT.md cannot gain a term this glossary silently ignores, and cannot
// lose one this glossary keeps explaining.

import type { GlossaryTerm } from './types';

/**
 * CONTEXT.md headings that are deliberately NOT mirrored, each with the reason.
 * Engineer- and operator-only vocabulary: a reader of the Help panel has no
 * use for the simulation harness's internals or a server projection's name.
 *
 * A row here is a reviewable diff line, which is the point — the test fails on
 * an allowlisted heading that no longer exists in CONTEXT.md, so this list
 * cannot rot quietly either.
 */
export const GLOSSARY_ALLOWLIST: Readonly<Record<string, string>> = Object.freeze({
  'User Management': 'Name of an admin feature set, not a concept a reader meets. The admin pages get summaries in T14.',
  'Coupon Template': 'Super-admin authoring tool for minting coupons; a reader only ever meets the resulting Coupon.',
  'Billing Charge': 'Internal accounting ledger record. A commissioner sees their receipts, never this term.',
  'Super-Admin Dashboard': 'Names an admin surface, not a concept. Covered by the per-tab page summaries in T14.',
  'Operations': 'Names one admin tab. Covered by that tab page summary in T14.',
  'Test Suite': 'Names one admin tab. Covered by that tab page summary in T14.',
  'Sim Run': 'Simulation harness vocabulary. Never reaches a member-facing or commissioner-facing surface.',
  'Test Pool': 'Simulation harness vocabulary. Test pools are excluded from every surface a reader can see.',
  'Scenario': 'Simulation fixture vocabulary; engineering only.',
  'Golden Scenario': 'Simulation fixture vocabulary; engineering only.',
  'Scenario Oracle': 'Simulation fixture vocabulary; engineering only.',
  'Health Snapshot': 'Operations probe result, read only on the admin Overview tab.',
  'Member Record': 'The storage shape behind the Roster. Readers meet it as the Roster, which is mirrored.',
  'Pool Homepage (Overview)': 'Duplicate CONTEXT.md heading for the same concept as "Pool Homepage", which is mirrored as pool-homepage.',
  'Profile Subject': 'Internal modeling term covering both a player and an Expert; readers meet each separately.',
  'Expert Picks': 'A deferred feature with no shipped surface. Mirror it when it ships, not before.',
  'Roster Summary': 'Server-maintained projection behind the roster figures. Readers meet the figures, not the projection.',
  'Commissioner Aggregate Stats': 'Internal name for the rollup behind the Manage My Pools figures. Readers meet the figures themselves.',
});

export const GLOSSARY: readonly GlossaryTerm[] = [
  {
    id: 'user',
    term: 'Account',
    short: 'Your sign-in to March Melee Pools. One account holds every pool you play in and every pool you run.',
    long: 'You sign in once, and the same account follows you into every pool.\n\nYou do not need a separate account to run a pool. The account you play with is the account you create pools with.',
    contextHeading: 'User',
    audience: ['member', 'commissioner', 'admin'],
    related: ['role'],
  },
  {
    id: 'role',
    term: 'Role',
    short: 'What your account is allowed to do across the whole site. Most people are a member.',
    long: 'Member is the default, and it is what you need to enter pools and make picks.\n\nCommissioner adds the ability to create and run your own pools. Two further roles exist for running the site itself, and you will not be given one by accident.\n\nA role is site-wide. Being named a co-commissioner in one pool does not change it.',
    contextHeading: 'Role',
    audience: ['member', 'commissioner', 'admin'],
    related: ['user', 'commissioner', 'co-commissioner', 'member'],
  },
  {
    id: 'activity-log',
    term: 'Activity log',
    short: 'A dated list of what a member has done on the site: signing in, joining a pool, submitting picks.',
    long: 'Each line is written at the moment the action happens, so nobody can edit the list afterwards.\n\nIt answers one question: what did this member do, and when.',
    contextHeading: 'Activity Log',
    audience: ['admin'],
    related: ['admin-audit-log'],
  },
  {
    id: 'admin-audit-log',
    term: 'Admin audit log',
    short: 'A dated record of every administrative action, kept from the point of view of whoever took it.',
    long: 'Where the activity log answers what happened to one member, this one answers what a single administrator did today.\n\nBoth are written at the moment of the action, and neither can be edited by anyone afterwards.',
    contextHeading: 'Admin Audit Log',
    audience: ['admin'],
    related: ['activity-log'],
  },
  {
    id: 'pool',
    term: 'Pool',
    short: 'One contest with one group of players — a bracket, a squares grid, a pick’em, a survivor, a margin, or a props pool.',
    long: 'A pool has one owner, who runs it, and any number of members, who play in it.\n\nEverything in a pool is scoped to that pool: its settings, its entry fee, its standings and its prizes. Nothing carries across from one pool to another except your own results history.',
    contextHeading: 'Pool',
    audience: ['member', 'commissioner', 'admin'],
    related: ['commissioner', 'member', 'entry', 'roster'],
  },
  {
    id: 'commissioner',
    term: 'Commissioner',
    short: 'The person who created and runs a pool. They set the rules, collect the entry fees, and pay out the prizes.',
    long: 'You are a commissioner in a pool you created. In every other pool you are a member.\n\nA commissioner decides the settings, invites players, marks who has paid, scores the results where scoring is not automatic, and records the payouts.\n\nThe money never passes through this site. A commissioner collects and pays out directly.',
    contextHeading: 'Commissioner',
    audience: ['member', 'commissioner', 'admin'],
    related: ['co-commissioner', 'pool', 'entry-fee'],
  },
  {
    id: 'co-commissioner',
    term: 'Co-commissioner',
    short: 'A member the pool owner has named to help run an NFL pool. Up to three per pool.',
    long: 'A co-commissioner does the day-to-day work: editing settings, extending a deadline, making a pick on someone’s behalf, scoring a week, sending invites and reminders, marking members paid, and recording payouts.\n\nThey cannot cancel, close or delete the pool, cannot touch billing, and cannot name other co-commissioners.\n\nIt applies to that one pool only. Being named a co-commissioner does not change your role anywhere else. Pick’em, survivor and margin pools have them; other formats do not.',
    contextHeading: 'Co-Commissioner',
    audience: ['member', 'commissioner', 'admin'],
    related: ['commissioner', 'role'],
  },
  {
    id: 'member',
    term: 'Member',
    short: 'Anyone who has joined a pool, whether or not they have played yet.',
    long: 'You become a member of a pool the moment you join it, and you appear on the roster from then on.\n\nBeing a member is about belonging to the pool and owing the entry fee. Making picks is separate — you can be a member with nothing entered yet.\n\nThe commissioner is a member of their own pool too.',
    contextHeading: 'Member',
    audience: ['member', 'commissioner', 'admin'],
    related: ['roster', 'entry', 'pool'],
  },
  {
    id: 'entry-fee',
    term: 'Entry fee',
    short: 'What each player pays the commissioner to join. You pay them directly — the site never holds the money.',
    long: 'The commissioner sets the entry fee when the pool is created, and everyone sees it before they join.\n\nYou pay the commissioner through whatever app you both use. This site records the amount and tracks who has paid, and nothing more.\n\nThis is separate from billing, which is what a commissioner pays to run the pool.',
    contextHeading: 'Entry Fee',
    audience: ['member', 'commissioner', 'admin'],
    related: ['payment-handle', 'paid-status', 'billing'],
  },
  {
    id: 'payment-handle',
    term: 'Payment handle',
    short: 'The commissioner’s name on a payment app — Venmo, Zelle, Cash App, PayPal or Google Pay — so you know where to send the fee.',
    long: 'A commissioner can list one or several. They are shown to members so nobody has to ask where to send the money.\n\nThe payment itself happens in that app, between the two of you. This site never moves entry fee money.',
    contextHeading: 'Payment Handle',
    audience: ['member', 'commissioner', 'admin'],
    related: ['entry-fee'],
  },
  {
    id: 'paid-status',
    term: 'Paid',
    short: 'The commissioner’s confirmation that a member has paid the entry fee. A member can never set it themselves.',
    long: 'This is the figure the pool runs on. Some pool types will not let an unpaid member submit an entry, so it has to be the commissioner’s word rather than the member’s.\n\nYour commissioner sets it. Site staff can also set it, which is how a mistake gets put right when a commissioner is unreachable.\n\nIf you have paid and it still shows unpaid, tell your commissioner — or mark it yourself as a payment claim, which lets them confirm it in one tap.',
    contextHeading: 'Paid Status',
    audience: ['member', 'commissioner', 'admin'],
    related: ['member-payment-claim', 'entry-fee'],
  },
  {
    id: 'member-payment-claim',
    term: 'Payment claim',
    short: 'Your own note that you have sent the entry fee. It tells the commissioner to look — it does not mark you paid.',
    long: 'A claim is an honour-system message, not a payment. It never unlocks anything on its own.\n\nYour commissioner reviews claims and confirms the ones that arrived, which is what actually marks you paid.',
    contextHeading: 'Member Payment Claim',
    audience: ['member', 'commissioner', 'admin'],
    related: ['paid-status', 'entry-fee'],
  },
  {
    id: 'billing',
    term: 'Billing',
    short: 'What a commissioner pays this site to run a pool. Nothing to do with entry fees.',
    long: 'Billing is between a commissioner and March Melee Pools, and is paid by card.\n\nEntry fees are between members and their commissioner, and never pass through here. The two never mix.\n\nMembers are never billed for anything.',
    contextHeading: 'Billing',
    audience: ['commissioner', 'admin'],
    related: ['entry-fee', 'bundle', 'pool-credit', 'coupon'],
  },
  {
    id: 'bundle',
    term: 'Bundle',
    short: 'A prepaid purchase covering several pools at once: either a set number of pool credits, or an unlimited pass for a term.',
    long: 'Buy a bundle when you know you will run more than one pool, because it is cheaper per pool than activating them one at a time.\n\nA credit bundle gives you a fixed number of pool credits to spend whenever you like. An unlimited pass covers as many pools as you want, until the term ends.',
    contextHeading: 'Bundle',
    audience: ['commissioner', 'admin'],
    related: ['pool-credit', 'unlimited-pass', 'billing'],
  },
  {
    id: 'pool-credit',
    term: 'Pool credit',
    short: 'One prepaid activation. Spend it to launch a pool instead of paying at checkout.',
    long: 'Credits come from buying a credit bundle. They do not expire on their own — an unspent credit stays yours.\n\nA credit can carry conditions, such as which pool format it covers or how many players that pool may have. Where it does, the condition is shown before you spend it.',
    contextHeading: 'Pool Credit',
    audience: ['commissioner', 'admin'],
    related: ['bundle', 'unlimited-pass', 'billing'],
  },
  {
    id: 'unlimited-pass',
    term: 'Unlimited pass',
    short: 'Launch as many pools as you like for a fixed term, usually a year.',
    long: 'Unlike pool credits, a pass runs on a clock: it covers everything you launch while it is live, and stops covering new pools when the term ends.\n\nPools you already launched under it are unaffected when it expires.',
    contextHeading: 'Unlimited Pass',
    audience: ['commissioner', 'admin'],
    related: ['bundle', 'pool-credit', 'billing'],
  },
  {
    id: 'coupon',
    term: 'Coupon',
    short: 'A code that takes money off what you pay to activate a pool or buy a bundle.',
    long: 'Enter it at checkout and the discount is shown before you pay.\n\nA coupon can be a percentage or a flat amount, and can be limited by date, by how many people use it, by how many times you use it, or to certain pool formats. Any limit that applies is shown when you enter the code.\n\nAn abandoned checkout does not use up your coupon.',
    contextHeading: 'Coupon',
    audience: ['commissioner', 'admin'],
    related: ['billing'],
  },
  {
    id: 'pool-draft',
    term: 'Draft pool',
    short: 'A pool you are still setting up in the wizard. It exists on this device only until you launch it.',
    long: 'You can leave the wizard and come back to a draft on the same device and browser.\n\nNobody can see or join a draft, and it is not a pool yet. Launching it is what creates the pool and opens it to members.\n\nBecause a draft is held on the device, clearing your browser data or moving to another device loses it.',
    contextHeading: 'Pool Draft',
    audience: ['commissioner', 'admin'],
    related: ['pool'],
  },
  {
    id: 'password-reset',
    term: 'Password reset',
    short: 'An email that lets you set a new password. You can request one yourself, or site staff can send it.',
    long: 'The email goes to the address on the account and contains a link that expires.\n\nNobody at March Melee Pools can see or set your password — sending the email is all anyone can do for you.',
    contextHeading: 'Password Reset',
    audience: ['member', 'commissioner', 'admin'],
  },
  {
    id: 'pool-lifecycle-state',
    term: 'Pool status',
    short: 'Where a pool is in its life: open, locked, live, final, or closed.',
    long: 'Open means it is still taking entries. Locked means entries are in and cannot be changed. Live means games are being played. Final means everything is scored and the results stand.\n\nClosed is different from the others: it means a commissioner or site staff has archived the pool and taken it out of active use.',
    contextHeading: 'Pool Lifecycle State',
    audience: ['member', 'commissioner', 'admin'],
    related: ['pool'],
  },
  {
    id: 'roster',
    term: 'Roster',
    short: 'Everyone in one pool, with what each owes and whether they have paid.',
    long: 'The roster is the list a commissioner works from: who is in, who owes what, and who has paid.\n\nIt includes every member who has joined, whether or not they have played, and it includes the commissioner. It is the same list behind both your own payments view and the commissioner’s payment ledger, so the two always agree.',
    contextHeading: 'Roster',
    audience: ['member', 'commissioner', 'admin'],
    related: ['member', 'paid-status', 'entry-fee'],
  },
  {
    id: 'entry',
    term: 'Entry',
    short: 'What you actually played: your picks, your bracket, or your squares. Separate from being a member.',
    long: 'Joining a pool makes you a member. Submitting picks creates an entry.\n\nSome pool types let one person hold more than one entry, so their name can appear several times in the standings.\n\nYou can be on the roster with no entry at all — that is a member who has not played yet.',
    contextHeading: 'Entry',
    audience: ['member', 'commissioner', 'admin'],
    related: ['member', 'roster', 'pool'],
  },
  {
    id: 'consensus',
    term: 'Consensus',
    short: 'How the crowd picked a game — the share who took each team. It is about picks, not about who will win.',
    long: 'Consensus tells you what other players did. It never predicts a result.\n\nThere are two kinds: consensus inside your own pool, and consensus across every pool on the site.\n\nDo not confuse it with live win probability, which is an estimate of the game’s outcome and has nothing to do with picks.',
    contextHeading: 'Consensus',
    audience: ['member', 'commissioner', 'admin'],
    related: ['pool-consensus', 'site-wide-consensus', 'live-win-probability'],
  },
  {
    id: 'pool-consensus',
    term: 'Pool consensus',
    short: 'Of the members in your pool who picked a game, the share who took each team. Visible at all times.',
    long: 'It updates as members submit, so you can see the split before the deadline.\n\nIt shows counts only. It never says who picked what, and no screen can work that out from it.\n\nIn a very small pool a lopsided split can come close to identifying someone. That is known and accepted — seeing the crowd is the point of the feature.',
    contextHeading: 'Pool Consensus',
    audience: ['member', 'commissioner', 'admin'],
    related: ['consensus', 'site-wide-consensus', 'pick-reveal'],
  },
  {
    id: 'pick-reveal',
    term: 'Pick reveal',
    short: 'When another member’s actual pick becomes visible to you — never before their own deadline has passed.',
    long: 'The rule is the same instant their deadline was, so nobody is ever shown a pick that could still be changed.\n\nIn a pick’em pool that locks game by game, each pick reveals as that game kicks off. In confidence mode, weekly-lock mode, survivor and margin, the whole week reveals at its single deadline.\n\nOnce a week reveals, every member of that pool can see it. Somebody outside the pool never can.',
    contextHeading: 'Pick Reveal',
    audience: ['member', 'commissioner', 'admin'],
    related: ['pool-consensus', 'entry'],
  },
  {
    id: 'site-wide-consensus',
    term: 'Site-wide consensus',
    short: 'How everyone on the site picked a game, added up across every pool of the same type.',
    long: 'A much larger sample than your own pool, which makes it a better read on what the field thinks.\n\nIt is counted separately for each pool type, never blended into one number, because a survivor pick and a pick’em pick mean different things.\n\nLike pool consensus, it is counts only — no individual pick is ever exposed.',
    contextHeading: 'Site-Wide Consensus',
    audience: ['member', 'commissioner', 'admin'],
    related: ['consensus', 'pool-consensus'],
  },
  {
    id: 'live-win-probability',
    term: 'Live win probability',
    short: 'An estimate of which team will win a game, from live game data. Nothing to do with how anyone picked.',
    long: 'It moves during the game as the score and situation change.\n\nIt sits next to consensus on the pool home screen, and the two answer different questions: this one is about the game, consensus is about the players.',
    contextHeading: 'Live Win Probability',
    audience: ['member', 'commissioner', 'admin'],
    related: ['consensus'],
  },
  {
    id: 'performance-stats',
    term: 'Performance stats',
    short: 'Your real record: weekly wins and losses, accuracy, where you ranked, and your streaks.',
    long: 'These are worked out when a week is scored, from what actually happened. Nothing here is estimated or filled in.\n\nWhere a screen compares you to a league average, that average is the real average of your pool or of the site — never a fixed number.',
    contextHeading: 'Performance Stats',
    audience: ['member', 'commissioner', 'admin'],
    related: ['player-profile', 'profit'],
  },
  {
    id: 'player-profile',
    term: 'Player profile',
    short: 'A page showing one player’s record across every pool they have played, plus their profit.',
    long: 'It shows performance over time, a weekly record, pick history, how they do team by team, and a yearly record.\n\nIt is deliberately limited: the pick history shows only picks that have already been scored, and the page never names which pools the player belongs to. That way a private pool stays private, even from someone reading a public profile.\n\nYou see more detail on your own profile, and so do people in the same pool as you.',
    contextHeading: 'Player Profile',
    audience: ['member', 'commissioner', 'admin'],
    related: ['performance-stats', 'profit', 'achievement', 'expert'],
  },
  {
    id: 'profit',
    term: 'Profit',
    short: 'Prizes recorded for you across all your pools, minus the entry fees you owe.',
    long: 'A prize counts towards profit as soon as your commissioner records it, whether or not they have handed the money over yet.\n\nThe money moves between people, not through this site, so profit is a record of what was recorded — not a balance you can withdraw.\n\nA pool whose payouts have not been recorded yet still counts its entry fee, and your profile says how many pools are still waiting, so the number is never quietly incomplete.',
    contextHeading: 'Profit',
    audience: ['member', 'commissioner', 'admin'],
    related: ['payout-record', 'entry-fee', 'player-profile'],
  },
  {
    id: 'payout-record',
    term: 'Payout record',
    short: 'Your commissioner’s written statement that a prize was awarded to someone, and whether it has been handed over.',
    long: 'Recording a payout is what turns a shown prize into a real one. Until then the figure on a recap is an estimate.\n\nThe site never invents a payout. If a commissioner has not recorded it, it does not exist.\n\nRecording the same prize twice records it once, and a rescore corrects the earlier record rather than adding a second.',
    contextHeading: 'Payout Record',
    audience: ['member', 'commissioner', 'admin'],
    related: ['weekly-prize', 'season-prize', 'profit'],
  },
  {
    id: 'weekly-prize',
    term: 'Weekly prize',
    short: 'What you are owed for your place in one scored week, in a pool that pays out weekly.',
    long: 'The weekly pot is the weekly share of the entry fees divided by the number of weeks in the season, split across the paying places. A tie splits the places it covers evenly.\n\nIt is worked out once, when the week is first scored, and the amount does not change afterwards. If the week is rescored, the places can change but the money does not.\n\nA week with no weekly pot shows no weekly prize.',
    contextHeading: 'Weekly Prize',
    audience: ['member', 'commissioner', 'admin'],
    related: ['season-prize', 'payout-record'],
  },
  {
    id: 'season-prize',
    term: 'Season prize',
    short: 'What you are owed for where your entry finished the season.',
    long: 'The season pot is the whole pot in a pool that pays out once, or the season half in a pool that pays weekly and seasonally.\n\nTies at the end of the season are broken by the pool’s own tie rules before the money is split. Whatever ties remain split their places evenly.\n\nLike a weekly prize, the amount is fixed when the season is finalised and does not move if results are corrected later.',
    contextHeading: 'Season Prize',
    audience: ['member', 'commissioner', 'admin'],
    related: ['weekly-prize', 'payout-record', 'season-finalization'],
  },
  {
    id: 'season-finalization',
    term: 'Season finalisation',
    short: 'Final places and season history are written automatically once the last week is scored. Nobody has to press anything.',
    long: 'It settles the competition, not the money. Recording payouts stays a decision your commissioner makes.\n\nIf a result is corrected afterwards, the final places are worked out again from the corrected results.\n\nThis is different from a commissioner closing a pool, which archives it and settles nothing.',
    contextHeading: 'Season Finalization',
    audience: ['member', 'commissioner', 'admin'],
    related: ['season-prize', 'pool-lifecycle-state'],
  },
  {
    id: 'expert',
    term: 'Expert',
    short: 'A published pick source — such as a computer ranking or the betting line — tracked against real results like a player.',
    long: 'An expert has a game-by-game record you can compare yourself against.\n\nAn expert plays in no pools, pays no entry fees, and has no profit. Only the picks and the record are real.',
    contextHeading: 'Expert',
    audience: ['member', 'commissioner', 'admin'],
    related: ['player-profile', 'performance-stats'],
  },
  {
    id: 'achievement',
    term: 'Achievement',
    short: 'A badge shown on your player profile.',
    long: 'Your profile displays the achievements you have earned.\n\nThe part that awards them is still to be built, so an honest empty state is what you will see for now.',
    contextHeading: 'Achievement',
    audience: ['member', 'commissioner', 'admin'],
    related: ['player-profile'],
  },
  {
    id: 'pool-homepage',
    term: 'Pool home',
    short: 'The landing view for one pool: its standings, deadlines, live scores, and only the cards that suit its type.',
    long: 'Every pool has exactly one home view, whatever its type. A survivor card appears only on a survivor pool, a margin card only on a margin pool.\n\nThe tab you are on is part of the address, so the browser Back button steps back through tabs instead of leaving the pool.\n\nThis is one pool. The place that lists all the pools you run is Manage My Pools.',
    contextHeading: 'Pool Homepage',
    audience: ['member', 'commissioner', 'admin'],
    related: ['pool', 'commissioner-hub'],
  },
  {
    id: 'commissioner-hub',
    term: 'Manage my pools',
    short: 'Every pool you run, in one place, with the totals across all of them.',
    long: 'Reached from Manage My Pools in the header. It lists each pool you own or help run, and sums up members, dues collected, dues expected, and payouts recorded.\n\nIt is not the same as My Entries, which lists the pools you play in. Most commissioners use both.',
    contextHeading: 'Commissioner Hub',
    audience: ['commissioner', 'admin'],
    related: ['pool-homepage', 'pool'],
  },
];
