"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.inspectPoolState = exports.generateTestReport = exports.validateTestResults = exports.generateTestScenario = exports.joinWaitlist = exports.managePlayoffEntry = exports.syncPlayoffPools = exports.onPlayoffConfigUpdate = exports.checkPlayoffScores = exports.updateGlobalPlayoffResults = exports.calculatePlayoffScores = exports.submitPlayoffPicks = exports.onAnnouncementCreated = exports.onGameComplete = exports.updateTournamentData = exports.markEntryPaidStatus = exports.submitBracketEntry = exports.updateBracketEntry = exports.createBracketEntry = exports.joinBracketPool = exports.publishBracketPool = exports.createBracketPool = exports.backfillPools = exports.toggleWinnerPaid = exports.recalculatePoolWinners = exports.createPool = exports.syncParticipantIndices = exports.claimByCode = exports.claimMySquares = exports.createClaimCode = exports.createParticipantProfile = exports.recalculateGlobalStats = exports.onPoolLocked = exports.autoLockPools = exports.onWinnerComputed = exports.runReminders = exports.syncAllUsers = exports.onUserCreated = exports.onAIRequest = exports.onWinnerUpdate = exports.simulateGameUpdate = exports.fixPoolScores = exports.syncGameStatus = exports.updatePropCard = exports.gradeProp = exports.purchasePropCard = exports.confirmPayment = exports.reserveSquare = exports.lockPool = void 0;
const admin = require("firebase-admin");
if (!admin.apps.length) {
    admin.initializeApp();
}
// Exported Cloud Functions
var poolParams_1 = require("./poolParams");
Object.defineProperty(exports, "lockPool", { enumerable: true, get: function () { return poolParams_1.lockPool; } });
var squares_1 = require("./squares");
Object.defineProperty(exports, "reserveSquare", { enumerable: true, get: function () { return squares_1.reserveSquare; } });
var confirmPayment_1 = require("./confirmPayment");
Object.defineProperty(exports, "confirmPayment", { enumerable: true, get: function () { return confirmPayment_1.confirmPayment; } });
var propBets_1 = require("./propBets");
Object.defineProperty(exports, "purchasePropCard", { enumerable: true, get: function () { return propBets_1.purchasePropCard; } });
Object.defineProperty(exports, "gradeProp", { enumerable: true, get: function () { return propBets_1.gradeProp; } });
Object.defineProperty(exports, "updatePropCard", { enumerable: true, get: function () { return propBets_1.updatePropCard; } });
var scoreUpdates_1 = require("./scoreUpdates");
Object.defineProperty(exports, "syncGameStatus", { enumerable: true, get: function () { return scoreUpdates_1.syncGameStatus; } });
Object.defineProperty(exports, "fixPoolScores", { enumerable: true, get: function () { return scoreUpdates_1.fixPoolScores; } });
Object.defineProperty(exports, "simulateGameUpdate", { enumerable: true, get: function () { return scoreUpdates_1.simulateGameUpdate; } });
var aiCommissioner_1 = require("./aiCommissioner");
Object.defineProperty(exports, "onWinnerUpdate", { enumerable: true, get: function () { return aiCommissioner_1.onWinnerUpdate; } });
Object.defineProperty(exports, "onAIRequest", { enumerable: true, get: function () { return aiCommissioner_1.onAIRequest; } });
var userSync_1 = require("./userSync");
Object.defineProperty(exports, "onUserCreated", { enumerable: true, get: function () { return userSync_1.onUserCreated; } });
Object.defineProperty(exports, "syncAllUsers", { enumerable: true, get: function () { return userSync_1.syncAllUsers; } });
var reminders_1 = require("./reminders");
Object.defineProperty(exports, "runReminders", { enumerable: true, get: function () { return reminders_1.runReminders; } });
Object.defineProperty(exports, "onWinnerComputed", { enumerable: true, get: function () { return reminders_1.onWinnerComputed; } });
var autoLock_1 = require("./autoLock"); // NEW: Dedicated 1-minute auto-lock scheduler
Object.defineProperty(exports, "autoLockPools", { enumerable: true, get: function () { return autoLock_1.autoLockPools; } });
var statsTrigger_1 = require("./statsTrigger");
Object.defineProperty(exports, "onPoolLocked", { enumerable: true, get: function () { return statsTrigger_1.onPoolLocked; } });
Object.defineProperty(exports, "recalculateGlobalStats", { enumerable: true, get: function () { return statsTrigger_1.recalculateGlobalStats; } });
var participant_1 = require("./participant");
Object.defineProperty(exports, "createParticipantProfile", { enumerable: true, get: function () { return participant_1.onUserCreated; } });
Object.defineProperty(exports, "createClaimCode", { enumerable: true, get: function () { return participant_1.createClaimCode; } });
Object.defineProperty(exports, "claimMySquares", { enumerable: true, get: function () { return participant_1.claimMySquares; } });
Object.defineProperty(exports, "claimByCode", { enumerable: true, get: function () { return participant_1.claimByCode; } });
Object.defineProperty(exports, "syncParticipantIndices", { enumerable: true, get: function () { return participant_1.syncParticipantIndices; } });
var poolOps_1 = require("./poolOps");
Object.defineProperty(exports, "createPool", { enumerable: true, get: function () { return poolOps_1.createPool; } });
Object.defineProperty(exports, "recalculatePoolWinners", { enumerable: true, get: function () { return poolOps_1.recalculatePoolWinners; } });
Object.defineProperty(exports, "toggleWinnerPaid", { enumerable: true, get: function () { return poolOps_1.toggleWinnerPaid; } });
var backfill_1 = require("./backfill");
Object.defineProperty(exports, "backfillPools", { enumerable: true, get: function () { return backfill_1.backfillPools; } });
var bracketPools_1 = require("./bracketPools");
Object.defineProperty(exports, "createBracketPool", { enumerable: true, get: function () { return bracketPools_1.createBracketPool; } });
Object.defineProperty(exports, "publishBracketPool", { enumerable: true, get: function () { return bracketPools_1.publishBracketPool; } });
Object.defineProperty(exports, "joinBracketPool", { enumerable: true, get: function () { return bracketPools_1.joinBracketPool; } });
var bracketEntries_1 = require("./bracketEntries");
Object.defineProperty(exports, "createBracketEntry", { enumerable: true, get: function () { return bracketEntries_1.createBracketEntry; } });
Object.defineProperty(exports, "updateBracketEntry", { enumerable: true, get: function () { return bracketEntries_1.updateBracketEntry; } });
Object.defineProperty(exports, "submitBracketEntry", { enumerable: true, get: function () { return bracketEntries_1.submitBracketEntry; } });
var bracketOps_1 = require("./bracketOps");
Object.defineProperty(exports, "markEntryPaidStatus", { enumerable: true, get: function () { return bracketOps_1.markEntryPaidStatus; } });
Object.defineProperty(exports, "updateTournamentData", { enumerable: true, get: function () { return bracketOps_1.updateTournamentData; } });
var postGameEmail_1 = require("./postGameEmail");
Object.defineProperty(exports, "onGameComplete", { enumerable: true, get: function () { return postGameEmail_1.onGameComplete; } });
var announcements_1 = require("./announcements");
Object.defineProperty(exports, "onAnnouncementCreated", { enumerable: true, get: function () { return announcements_1.onAnnouncementCreated; } });
var playoffPools_1 = require("./playoffPools");
Object.defineProperty(exports, "submitPlayoffPicks", { enumerable: true, get: function () { return playoffPools_1.submitPlayoffPicks; } });
Object.defineProperty(exports, "calculatePlayoffScores", { enumerable: true, get: function () { return playoffPools_1.calculatePlayoffScores; } });
Object.defineProperty(exports, "updateGlobalPlayoffResults", { enumerable: true, get: function () { return playoffPools_1.updateGlobalPlayoffResults; } });
Object.defineProperty(exports, "checkPlayoffScores", { enumerable: true, get: function () { return playoffPools_1.checkPlayoffScores; } });
Object.defineProperty(exports, "onPlayoffConfigUpdate", { enumerable: true, get: function () { return playoffPools_1.onPlayoffConfigUpdate; } });
Object.defineProperty(exports, "syncPlayoffPools", { enumerable: true, get: function () { return playoffPools_1.syncPlayoffPools; } });
Object.defineProperty(exports, "managePlayoffEntry", { enumerable: true, get: function () { return playoffPools_1.managePlayoffEntry; } });
var waitlist_1 = require("./waitlist");
Object.defineProperty(exports, "joinWaitlist", { enumerable: true, get: function () { return waitlist_1.joinWaitlist; } });
var aiTesting_1 = require("./aiTesting");
Object.defineProperty(exports, "generateTestScenario", { enumerable: true, get: function () { return aiTesting_1.generateTestScenario; } });
Object.defineProperty(exports, "validateTestResults", { enumerable: true, get: function () { return aiTesting_1.validateTestResults; } });
Object.defineProperty(exports, "generateTestReport", { enumerable: true, get: function () { return aiTesting_1.generateTestReport; } });
var debug_1 = require("./debug");
Object.defineProperty(exports, "inspectPoolState", { enumerable: true, get: function () { return debug_1.inspectPoolState; } });
//# sourceMappingURL=index.js.map