import type { GameState } from './types';

export const DEFAULT_SQUARES = Array.from({ length: 100 }, (_, i) => ({
  id: i,
  owner: null,
  isPaid: false
}));

export const createNewPool = (name: string = 'New March Melee Pool', ownerId?: string, managerName: string = '', contactEmail: string = ''): GameState => ({
  id: Math.random().toString(36).substring(2, 9),
  type: 'SQUARES',
  name,
  urlSlug: Math.random().toString(36).substring(2, 7),
  contactEmail: contactEmail,
  managerName: managerName,
  paymentInstructions: 'Venmo @YourName to participate. Payments due before kickoff.',
  theme: 'Default Theme',
  gridUsername: '',
  gridPassword: '',
  paymentHandles: {
    venmo: '',
    zelle: ''
  },

  homeTeam: '',
  awayTeam: '',
  league: 'nfl',
  homeTeamLogo: '',
  awayTeamLogo: '',
  gameId: undefined,

  costPerSquare: 10,
  maxSquaresPerPlayer: 10,
  lockGrid: false,
  numberSets: 1,

  gridSize: '10x10',
  numberTheSquares: true,
  showPaid: true,

  emailConfirmation: 'Email Confirmation',
  notifyAdminFull: true,
  emailNumbersGenerated: true,

  collectReferral: true,
  collectPhone: false,
  collectNotes: true,
  collectAddress: false,

  additionalLinks: [],

  requireCode: false,
  enableSecondaryAdmins: false,

  isPublic: true,
  squares: Array.from({ length: 100 }, (_, i) => ({ id: i, owner: null, isPaid: false })), // Deep copy
  axisNumbers: null,
  scores: {
    current: null,
    q1: null,
    half: null,
    q3: null,
    final: null,
    gameStatus: 'pre',
    clock: '0:00',
    startTime: undefined, // Will be filled by sync
  },
  scoreEvents: [],
  scoreChangePayoutAmount: 5, // Default $5 per score change
  payouts: {
    q1: 20,
    half: 20,
    q3: 20,
    final: 40,
  },
  charity: {
    enabled: false,
    name: '',
    description: '',
    url: '',
    percentage: 0
  },
  includeOvertime: true,
  isLocked: false,
  ruleVariations: {
    reverseWinners: false,
    quarterlyRollover: true,
    scoreChangePayout: false,
    unclaimedFinalPrizeStrategy: 'last_winner',
  },
  ownerId
});

export const PERIOD_LABELS: Record<string, string> = {
  q1: '1st Quarter',
  half: 'Halftime',
  q3: '3rd Quarter',
  final: 'Final Score',
};

// NFL Team Data for Logos
export const NFL_TEAMS: Record<string, { name: string; abbr: string; logo: string }> = {
  'ari': { name: 'Cardinals', abbr: 'ARI', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png' },
  'atl': { name: 'Falcons', abbr: 'ATL', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png' },
  'bal': { name: 'Ravens', abbr: 'BAL', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png' },
  'buf': { name: 'Bills', abbr: 'BUF', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png' },
  'car': { name: 'Panthers', abbr: 'CAR', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png' },
  'chi': { name: 'Bears', abbr: 'CHI', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png' },
  'cin': { name: 'Bengals', abbr: 'CIN', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png' },
  'cle': { name: 'Browns', abbr: 'CLE', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png' },
  'dal': { name: 'Cowboys', abbr: 'DAL', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png' },
  'den': { name: 'Broncos', abbr: 'DEN', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png' },
  'det': { name: 'Lions', abbr: 'DET', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png' },
  'gb': { name: 'Packers', abbr: 'GB', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png' },
  'hou': { name: 'Texans', abbr: 'HOU', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png' },
  'ind': { name: 'Colts', abbr: 'IND', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  'jax': { name: 'Jaguars', abbr: 'JAX', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png' },
  'kc': { name: 'Chiefs', abbr: 'KC', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png' },
  'lac': { name: 'Chargers', abbr: 'LAC', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png' },
  'lar': { name: 'Rams', abbr: 'LAR', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png' },
  'lv': { name: 'Raiders', abbr: 'LV', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png' },
  'mia': { name: 'Dolphins', abbr: 'MIA', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png' },
  'min': { name: 'Vikings', abbr: 'MIN', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png' },
  'ne': { name: 'Patriots', abbr: 'NE', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png' },
  'no': { name: 'Saints', abbr: 'NO', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png' },
  'nyg': { name: 'Giants', abbr: 'NYG', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png' },
  'nyj': { name: 'Jets', abbr: 'NYJ', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png' },
  'phi': { name: 'Eagles', abbr: 'PHI', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png' },
  'pit': { name: 'Steelers', abbr: 'PIT', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png' },
  'sea': { name: 'Seahawks', abbr: 'SEA', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png' },
  'sf': { name: '49ers', abbr: 'SF', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png' },
  'tb': { name: 'Buccaneers', abbr: 'TB', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png' },
  'ten': { name: 'Titans', abbr: 'TEN', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png' },
  'wsh': { name: 'Commanders', abbr: 'WSH', logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png' },
};

// NCAA Team Data for Logos (Top teams)
// NCAA Team Data for Logos (Comprehensive)
export const NCAA_TEAMS: Record<string, {name: string, id: string, logo: string}> = {
  'abilenechrstn': { name: "Abilene Christian Wildcats", id: "2000", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2000.png" },
  'acu': { name: "Abilene Christian Wildcats", id: "2000", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2000.png" },
  'airforce': { name: "Air Force Falcons", id: "2005", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png" },
  'af': { name: "Air Force Falcons", id: "2005", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png" },
  'akron': { name: "Akron Zips", id: "2006", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png" },
  'akr': { name: "Akron Zips", id: "2006", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png" },
  'alabamaam': { name: "Alabama A&M Bulldogs", id: "2010", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2010.png" },
  'aamu': { name: "Alabama A&M Bulldogs", id: "2010", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2010.png" },
  'alabama': { name: "Alabama Crimson Tide", id: "333", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png" },
  'ala': { name: "Alabama Crimson Tide", id: "333", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png" },
  'alabamast': { name: "Alabama State Hornets", id: "2011", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2011.png" },
  'alst': { name: "Alabama State Hornets", id: "2011", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2011.png" },
  'alcornst': { name: "Alcorn State Braves", id: "2016", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2016.png" },
  'alcn': { name: "Alcorn State Braves", id: "2016", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2016.png" },
  'american': { name: "American University Eagles", id: "44", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/44.png" },
  'amer': { name: "American University Eagles", id: "44", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/44.png" },
  'appstate': { name: "App State Mountaineers", id: "2026", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png" },
  'app': { name: "App State Mountaineers", id: "2026", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png" },
  'arizonast': { name: "Arizona State Sun Devils", id: "9", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png" },
  'asu': { name: "Arizona State Sun Devils", id: "9", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png" },
  'arizona': { name: "Arizona Wildcats", id: "12", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png" },
  'ariz': { name: "Arizona Wildcats", id: "12", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png" },
  'arkansas': { name: "Arkansas Razorbacks", id: "8", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png" },
  'ark': { name: "Arkansas Razorbacks", id: "8", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png" },
  'arkansasst': { name: "Arkansas State Red Wolves", id: "2032", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png" },
  'arst': { name: "Arkansas State Red Wolves", id: "2032", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png" },
  'arpinebluff': { name: "Arkansas-Pine Bluff Golden Lions", id: "2029", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png" },
  'uapb': { name: "Arkansas-Pine Bluff Golden Lions", id: "2029", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png" },
  'army': { name: "Army Black Knights", id: "349", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/349.png" },
  'auburn': { name: "Auburn Tigers", id: "2", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png" },
  'aub': { name: "Auburn Tigers", id: "2", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png" },
  'austinpeay': { name: "Austin Peay Governors", id: "2046", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2046.png" },
  'apsu': { name: "Austin Peay Governors", id: "2046", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2046.png" },
  'byu': { name: "BYU Cougars", id: "252", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/252.png" },
  'ballstate': { name: "Ball State Cardinals", id: "2050", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png" },
  'ball': { name: "Ball State Cardinals", id: "2050", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png" },
  'baylor': { name: "Baylor Bears", id: "239", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png" },
  'bay': { name: "Baylor Bears", id: "239", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png" },
  'bellarmine': { name: "Bellarmine Knights", id: "91", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/91.png" },
  'bell': { name: "Bellarmine Knights", id: "91", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/91.png" },
  'belmont': { name: "Belmont Bruins", id: "2057", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2057.png" },
  'bel': { name: "Belmont Bruins", id: "2057", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2057.png" },
  'bethune': { name: "Bethune-Cookman Wildcats", id: "2065", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2065.png" },
  'bcu': { name: "Bethune-Cookman Wildcats", id: "2065", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2065.png" },
  'binghamton': { name: "Binghamton Bearcats", id: "2066", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2066.png" },
  'bing': { name: "Binghamton Bearcats", id: "2066", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2066.png" },
  'boisest': { name: "Boise State Broncos", id: "68", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png" },
  'bois': { name: "Boise State Broncos", id: "68", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png" },
  'bostoncollege': { name: "Boston College Eagles", id: "103", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png" },
  'bc': { name: "Boston College Eagles", id: "103", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png" },
  'bostonu': { name: "Boston University Terriers", id: "104", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/104.png" },
  'bu': { name: "Boston University Terriers", id: "104", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/104.png" },
  'bowlinggreen': { name: "Bowling Green Falcons", id: "189", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png" },
  'bgsu': { name: "Bowling Green Falcons", id: "189", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png" },
  'bradley': { name: "Bradley Braves", id: "71", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/71.png" },
  'brad': { name: "Bradley Braves", id: "71", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/71.png" },
  'brown': { name: "Brown Bears", id: "225", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/225.png" },
  'brwn': { name: "Brown Bears", id: "225", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/225.png" },
  'bryant': { name: "Bryant Bulldogs", id: "2803", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2803.png" },
  'bry': { name: "Bryant Bulldogs", id: "2803", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2803.png" },
  'bucknell': { name: "Bucknell Bison", id: "2083", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2083.png" },
  'buck': { name: "Bucknell Bison", id: "2083", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2083.png" },
  'buffalo': { name: "Buffalo Bulls", id: "2084", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png" },
  'buf': { name: "Buffalo Bulls", id: "2084", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png" },
  'butler': { name: "Butler Bulldogs", id: "2086", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png" },
  'but': { name: "Butler Bulldogs", id: "2086", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png" },
  'calpoly': { name: "Cal Poly Mustangs", id: "13", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/13.png" },
  'cp': { name: "Cal Poly Mustangs", id: "13", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/13.png" },
  'bakersfield': { name: "Cal State Bakersfield Roadrunners", id: "2934", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2934.png" },
  'csub': { name: "Cal State Bakersfield Roadrunners", id: "2934", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2934.png" },
  'fullerton': { name: "Cal State Fullerton Titans", id: "2239", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2239.png" },
  'csuf': { name: "Cal State Fullerton Titans", id: "2239", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2239.png" },
  'csunorthridge': { name: "Cal State Northridge Matadors", id: "2463", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2463.png" },
  'csun': { name: "Cal State Northridge Matadors", id: "2463", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2463.png" },
  'cabaptist': { name: "California Baptist Lancers", id: "2856", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2856.png" },
  'cbu': { name: "California Baptist Lancers", id: "2856", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2856.png" },
  'california': { name: "California Golden Bears", id: "25", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png" },
  'cal': { name: "California Golden Bears", id: "25", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png" },
  'campbell': { name: "Campbell Fighting Camels", id: "2097", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2097.png" },
  'cam': { name: "Campbell Fighting Camels", id: "2097", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2097.png" },
  'canisius': { name: "Canisius Golden Griffins", id: "2099", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png" },
  'can': { name: "Canisius Golden Griffins", id: "2099", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png" },
  'carkansas': { name: "Central Arkansas Bears", id: "2110", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2110.png" },
  'cark': { name: "Central Arkansas Bears", id: "2110", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2110.png" },
  'cconnecticut': { name: "Central Connecticut Blue Devils", id: "2115", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2115.png" },
  'ccsu': { name: "Central Connecticut Blue Devils", id: "2115", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2115.png" },
  'cmichigan': { name: "Central Michigan Chippewas", id: "2117", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png" },
  'cmu': { name: "Central Michigan Chippewas", id: "2117", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png" },
  'charleston': { name: "Charleston Cougars", id: "232", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/232.png" },
  'cofc': { name: "Charleston Cougars", id: "232", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/232.png" },
  'charlestonso': { name: "Charleston Southern Buccaneers", id: "2127", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2127.png" },
  'chso': { name: "Charleston Southern Buccaneers", id: "2127", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2127.png" },
  'charlotte': { name: "Charlotte 49ers", id: "2429", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png" },
  'clt': { name: "Charlotte 49ers", id: "2429", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png" },
  'chattanooga': { name: "Chattanooga Mocs", id: "236", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/236.png" },
  'utc': { name: "Chattanooga Mocs", id: "236", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/236.png" },
  'chicagost': { name: "Chicago State Cougars", id: "2130", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2130.png" },
  'chst': { name: "Chicago State Cougars", id: "2130", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2130.png" },
  'cincinnati': { name: "Cincinnati Bearcats", id: "2132", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png" },
  'cin': { name: "Cincinnati Bearcats", id: "2132", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png" },
  'clemson': { name: "Clemson Tigers", id: "228", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/228.png" },
  'clem': { name: "Clemson Tigers", id: "228", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/228.png" },
  'clevelandst': { name: "Cleveland State Vikings", id: "325", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/325.png" },
  'cle': { name: "Cleveland State Vikings", id: "325", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/325.png" },
  'coastal': { name: "Coastal Carolina Chanticleers", id: "324", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png" },
  'ccu': { name: "Coastal Carolina Chanticleers", id: "324", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png" },
  'colgate': { name: "Colgate Raiders", id: "2142", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png" },
  'colg': { name: "Colgate Raiders", id: "2142", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png" },
  'colorado': { name: "Colorado Buffaloes", id: "38", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png" },
  'colo': { name: "Colorado Buffaloes", id: "38", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png" },
  'coloradost': { name: "Colorado State Rams", id: "36", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/36.png" },
  'csu': { name: "Colorado State Rams", id: "36", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/36.png" },
  'columbia': { name: "Columbia Lions", id: "171", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/171.png" },
  'colu': { name: "Columbia Lions", id: "171", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/171.png" },
  'coppinst': { name: "Coppin State Eagles", id: "2154", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2154.png" },
  'copp': { name: "Coppin State Eagles", id: "2154", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2154.png" },
  'cornell': { name: "Cornell Big Red", id: "172", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/172.png" },
  'cor': { name: "Cornell Big Red", id: "172", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/172.png" },
  'creighton': { name: "Creighton Bluejays", id: "156", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png" },
  'crei': { name: "Creighton Bluejays", id: "156", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png" },
  'dartmouth': { name: "Dartmouth Big Green", id: "159", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/159.png" },
  'dart': { name: "Dartmouth Big Green", id: "159", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/159.png" },
  'davidson': { name: "Davidson Wildcats", id: "2166", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2166.png" },
  'dav': { name: "Davidson Wildcats", id: "2166", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2166.png" },
  'dayton': { name: "Dayton Flyers", id: "2168", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png" },
  'day': { name: "Dayton Flyers", id: "2168", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png" },
  'depaul': { name: "DePaul Blue Demons", id: "305", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/305.png" },
  'dep': { name: "DePaul Blue Demons", id: "305", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/305.png" },
  'delaware': { name: "Delaware Blue Hens", id: "48", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/48.png" },
  'del': { name: "Delaware Blue Hens", id: "48", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/48.png" },
  'delawarest': { name: "Delaware State Hornets", id: "2169", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2169.png" },
  'dsu': { name: "Delaware State Hornets", id: "2169", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2169.png" },
  'denver': { name: "Denver Pioneers", id: "2172", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2172.png" },
  'den': { name: "Denver Pioneers", id: "2172", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2172.png" },
  'detroitmercy': { name: "Detroit Mercy Titans", id: "2174", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2174.png" },
  'detm': { name: "Detroit Mercy Titans", id: "2174", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2174.png" },
  'drake': { name: "Drake Bulldogs", id: "2181", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png" },
  'drke': { name: "Drake Bulldogs", id: "2181", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png" },
  'drexel': { name: "Drexel Dragons", id: "2182", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2182.png" },
  'drex': { name: "Drexel Dragons", id: "2182", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2182.png" },
  'duke': { name: "Duke Blue Devils", id: "150", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png" },
  'duquesne': { name: "Duquesne Dukes", id: "2184", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png" },
  'duq': { name: "Duquesne Dukes", id: "2184", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png" },
  'eastcarolina': { name: "East Carolina Pirates", id: "151", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/151.png" },
  'ecu': { name: "East Carolina Pirates", id: "151", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/151.png" },
  'etsu': { name: "East Tennessee State Buccaneers", id: "2193", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2193.png" },
  'etexasam': { name: "East Texas A&M Lions", id: "2837", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2837.png" },
  'etam': { name: "East Texas A&M Lions", id: "2837", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2837.png" },
  'eillinois': { name: "Eastern Illinois Panthers", id: "2197", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2197.png" },
  'eiu': { name: "Eastern Illinois Panthers", id: "2197", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2197.png" },
  'ekentucky': { name: "Eastern Kentucky Colonels", id: "2198", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2198.png" },
  'eku': { name: "Eastern Kentucky Colonels", id: "2198", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2198.png" },
  'emichigan': { name: "Eastern Michigan Eagles", id: "2199", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png" },
  'emu': { name: "Eastern Michigan Eagles", id: "2199", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png" },
  'ewashington': { name: "Eastern Washington Eagles", id: "331", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/331.png" },
  'ewu': { name: "Eastern Washington Eagles", id: "331", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/331.png" },
  'elon': { name: "Elon Phoenix", id: "2210", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2210.png" },
  'evansville': { name: "Evansville Purple Aces", id: "339", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/339.png" },
  'evan': { name: "Evansville Purple Aces", id: "339", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/339.png" },
  'fairfield': { name: "Fairfield Stags", id: "2217", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2217.png" },
  'fair': { name: "Fairfield Stags", id: "2217", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2217.png" },
  'fdu': { name: "Fairleigh Dickinson Knights", id: "161", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/161.png" },
  'floridaam': { name: "Florida A&M Rattlers", id: "50", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/50.png" },
  'famu': { name: "Florida A&M Rattlers", id: "50", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/50.png" },
  'fau': { name: "Florida Atlantic Owls", id: "2226", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png" },
  'florida': { name: "Florida Gators", id: "57", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png" },
  'fla': { name: "Florida Gators", id: "57", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png" },
  'fgcu': { name: "Florida Gulf Coast Eagles", id: "526", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/526.png" },
  'fiu': { name: "Florida International Panthers", id: "2229", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png" },
  'floridast': { name: "Florida State Seminoles", id: "52", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png" },
  'fsu': { name: "Florida State Seminoles", id: "52", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png" },
  'fordham': { name: "Fordham Rams", id: "2230", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2230.png" },
  'for': { name: "Fordham Rams", id: "2230", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2230.png" },
  'fresnost': { name: "Fresno State Bulldogs", id: "278", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/278.png" },
  'fres': { name: "Fresno State Bulldogs", id: "278", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/278.png" },
  'furman': { name: "Furman Paladins", id: "231", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png" },
  'fur': { name: "Furman Paladins", id: "231", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png" },
  'gardnerwebb': { name: "Gardner-Webb Runnin' Bulldogs", id: "2241", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png" },
  'gweb': { name: "Gardner-Webb Runnin' Bulldogs", id: "2241", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png" },
  'georgemason': { name: "George Mason Patriots", id: "2244", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png" },
  'gmu': { name: "George Mason Patriots", id: "2244", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png" },
  'gwashington': { name: "George Washington Revolutionaries", id: "45", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/45.png" },
  'gw': { name: "George Washington Revolutionaries", id: "45", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/45.png" },
  'georgetown': { name: "Georgetown Hoyas", id: "46", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/46.png" },
  'gtwn': { name: "Georgetown Hoyas", id: "46", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/46.png" },
  'georgia': { name: "Georgia Bulldogs", id: "61", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/61.png" },
  'uga': { name: "Georgia Bulldogs", id: "61", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/61.png" },
  'gasouthern': { name: "Georgia Southern Eagles", id: "290", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/290.png" },
  'gaso': { name: "Georgia Southern Eagles", id: "290", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/290.png" },
  'georgiast': { name: "Georgia State Panthers", id: "2247", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png" },
  'gast': { name: "Georgia State Panthers", id: "2247", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png" },
  'georgiatech': { name: "Georgia Tech Yellow Jackets", id: "59", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png" },
  'gt': { name: "Georgia Tech Yellow Jackets", id: "59", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png" },
  'gonzaga': { name: "Gonzaga Bulldogs", id: "2250", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png" },
  'gonz': { name: "Gonzaga Bulldogs", id: "2250", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png" },
  'grambling': { name: "Grambling Tigers", id: "2755", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png" },
  'gram': { name: "Grambling Tigers", id: "2755", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png" },
  'grandcanyon': { name: "Grand Canyon Lopes", id: "2253", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png" },
  'gcu': { name: "Grand Canyon Lopes", id: "2253", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png" },
  'greenbay': { name: "Green Bay Phoenix", id: "2739", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png" },
  'gb': { name: "Green Bay Phoenix", id: "2739", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png" },
  'hampton': { name: "Hampton Pirates", id: "2261", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2261.png" },
  'hamp': { name: "Hampton Pirates", id: "2261", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2261.png" },
  'harvard': { name: "Harvard Crimson", id: "108", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/108.png" },
  'harv': { name: "Harvard Crimson", id: "108", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/108.png" },
  'hawaii': { name: "Hawai'i Rainbow Warriors", id: "62", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png" },
  'haw': { name: "Hawai'i Rainbow Warriors", id: "62", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png" },
  'highpoint': { name: "High Point Panthers", id: "2272", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2272.png" },
  'hpu': { name: "High Point Panthers", id: "2272", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2272.png" },
  'hofstra': { name: "Hofstra Pride", id: "2275", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2275.png" },
  'hof': { name: "Hofstra Pride", id: "2275", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2275.png" },
  'holycross': { name: "Holy Cross Crusaders", id: "107", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/107.png" },
  'hc': { name: "Holy Cross Crusaders", id: "107", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/107.png" },
  'houchristian': { name: "Houston Christian Huskies", id: "2277", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2277.png" },
  'hcu': { name: "Houston Christian Huskies", id: "2277", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2277.png" },
  'houston': { name: "Houston Cougars", id: "248", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png" },
  'hou': { name: "Houston Cougars", id: "248", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png" },
  'howard': { name: "Howard Bison", id: "47", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/47.png" },
  'how': { name: "Howard Bison", id: "47", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/47.png" },
  'iuindy': { name: "IU Indianapolis Jaguars", id: "85", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/85.png" },
  'iuin': { name: "IU Indianapolis Jaguars", id: "85", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/85.png" },
  'idahost': { name: "Idaho State Bengals", id: "304", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/304.png" },
  'idst': { name: "Idaho State Bengals", id: "304", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/304.png" },
  'idaho': { name: "Idaho Vandals", id: "70", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/70.png" },
  'idho': { name: "Idaho Vandals", id: "70", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/70.png" },
  'illinois': { name: "Illinois Fighting Illini", id: "356", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png" },
  'ill': { name: "Illinois Fighting Illini", id: "356", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png" },
  'illinoisst': { name: "Illinois State Redbirds", id: "2287", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2287.png" },
  'ilst': { name: "Illinois State Redbirds", id: "2287", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2287.png" },
  'incarnateword': { name: "Incarnate Word Cardinals", id: "2916", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2916.png" },
  'uiw': { name: "Incarnate Word Cardinals", id: "2916", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2916.png" },
  'indiana': { name: "Indiana Hoosiers", id: "84", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png" },
  'iu': { name: "Indiana Hoosiers", id: "84", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png" },
  'indianast': { name: "Indiana State Sycamores", id: "282", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/282.png" },
  'inst': { name: "Indiana State Sycamores", id: "282", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/282.png" },
  'iona': { name: "Iona Gaels", id: "314", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/314.png" },
  'iowa': { name: "Iowa Hawkeyes", id: "2294", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png" },
  'iowastate': { name: "Iowa State Cyclones", id: "66", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png" },
  'isu': { name: "Iowa State Cyclones", id: "66", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png" },
  'jacksonst': { name: "Jackson State Tigers", id: "2296", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2296.png" },
  'jkst': { name: "Jackson State Tigers", id: "2296", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2296.png" },
  'jacksonville': { name: "Jacksonville Dolphins", id: "294", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/294.png" },
  'jax': { name: "Jacksonville Dolphins", id: "294", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/294.png" },
  'jaxstate': { name: "Jacksonville State Gamecocks", id: "55", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/55.png" },
  'jxst': { name: "Jacksonville State Gamecocks", id: "55", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/55.png" },
  'jamesmadison': { name: "James Madison Dukes", id: "256", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png" },
  'jmu': { name: "James Madison Dukes", id: "256", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png" },
  'kansascity': { name: "Kansas City Roos", id: "140", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/140.png" },
  'kc': { name: "Kansas City Roos", id: "140", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/140.png" },
  'kansas': { name: "Kansas Jayhawks", id: "2305", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png" },
  'ku': { name: "Kansas Jayhawks", id: "2305", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png" },
  'kansasst': { name: "Kansas State Wildcats", id: "2306", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png" },
  'ksu': { name: "Kansas State Wildcats", id: "2306", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png" },
  'kennesawst': { name: "Kennesaw State Owls", id: "338", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png" },
  'kenn': { name: "Kennesaw State Owls", id: "338", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png" },
  'kentstate': { name: "Kent State Golden Flashes", id: "2309", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png" },
  'kent': { name: "Kent State Golden Flashes", id: "2309", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png" },
  'kentucky': { name: "Kentucky Wildcats", id: "96", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png" },
  'uk': { name: "Kentucky Wildcats", id: "96", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png" },
  'lsu': { name: "LSU Tigers", id: "99", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/99.png" },
  'lasalle': { name: "La Salle Explorers", id: "2325", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2325.png" },
  'las': { name: "La Salle Explorers", id: "2325", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2325.png" },
  'lafayette': { name: "Lafayette Leopards", id: "322", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/322.png" },
  'laf': { name: "Lafayette Leopards", id: "322", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/322.png" },
  'lamar': { name: "Lamar Cardinals", id: "2320", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2320.png" },
  'lam': { name: "Lamar Cardinals", id: "2320", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2320.png" },
  'lemoyne': { name: "Le Moyne Dolphins", id: "2330", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2330.png" },
  'lem': { name: "Le Moyne Dolphins", id: "2330", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2330.png" },
  'lehigh': { name: "Lehigh Mountain Hawks", id: "2329", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2329.png" },
  'leh': { name: "Lehigh Mountain Hawks", id: "2329", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2329.png" },
  'liberty': { name: "Liberty Flames", id: "2335", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png" },
  'lib': { name: "Liberty Flames", id: "2335", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png" },
  'lipscomb': { name: "Lipscomb Bisons", id: "288", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/288.png" },
  'lip': { name: "Lipscomb Bisons", id: "288", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/288.png" },
  'littlerock': { name: "Little Rock Trojans", id: "2031", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2031.png" },
  'lr': { name: "Little Rock Trojans", id: "2031", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2031.png" },
  'longbeachst': { name: "Long Beach State Beach", id: "299", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/299.png" },
  'lbsu': { name: "Long Beach State Beach", id: "299", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/299.png" },
  'longisland': { name: "Long Island University Sharks", id: "112358", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/112358.png" },
  'liu': { name: "Long Island University Sharks", id: "112358", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/112358.png" },
  'longwood': { name: "Longwood Lancers", id: "2344", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png" },
  'long': { name: "Longwood Lancers", id: "2344", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png" },
  'louisiana': { name: "Louisiana Ragin' Cajuns", id: "309", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png" },
  'ul': { name: "Louisiana Ragin' Cajuns", id: "309", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png" },
  'louisianatech': { name: "Louisiana Tech Bulldogs", id: "2348", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png" },
  'lt': { name: "Louisiana Tech Bulldogs", id: "2348", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png" },
  'louisville': { name: "Louisville Cardinals", id: "97", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png" },
  'lou': { name: "Louisville Cardinals", id: "97", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png" },
  'loyolachicago': { name: "Loyola Chicago Ramblers", id: "2350", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2350.png" },
  'luc': { name: "Loyola Chicago Ramblers", id: "2350", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2350.png" },
  'loyolamd': { name: "Loyola Maryland Greyhounds", id: "2352", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2352.png" },
  'l-md': { name: "Loyola Maryland Greyhounds", id: "2352", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2352.png" },
  'lmu': { name: "Loyola Marymount Lions", id: "2351", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2351.png" },
  'maine': { name: "Maine Black Bears", id: "311", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/311.png" },
  'me': { name: "Maine Black Bears", id: "311", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/311.png" },
  'manhattan': { name: "Manhattan Jaspers", id: "2363", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2363.png" },
  'man': { name: "Manhattan Jaspers", id: "2363", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2363.png" },
  'marist': { name: "Marist Red Foxes", id: "2368", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2368.png" },
  'mrst': { name: "Marist Red Foxes", id: "2368", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2368.png" },
  'marquette': { name: "Marquette Golden Eagles", id: "269", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/269.png" },
  'marq': { name: "Marquette Golden Eagles", id: "269", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/269.png" },
  'marshall': { name: "Marshall Thundering Herd", id: "276", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png" },
  'mrsh': { name: "Marshall Thundering Herd", id: "276", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png" },
  'mdeastern': { name: "Maryland Eastern Shore Hawks", id: "2379", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2379.png" },
  'umes': { name: "Maryland Eastern Shore Hawks", id: "2379", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2379.png" },
  'maryland': { name: "Maryland Terrapins", id: "120", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png" },
  'md': { name: "Maryland Terrapins", id: "120", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png" },
  'umass': { name: "Massachusetts Minutemen", id: "113", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png" },
  'mass': { name: "Massachusetts Minutemen", id: "113", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png" },
  'mcneese': { name: "McNeese Cowboys", id: "2377", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2377.png" },
  'mcn': { name: "McNeese Cowboys", id: "2377", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2377.png" },
  'memphis': { name: "Memphis Tigers", id: "235", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png" },
  'mem': { name: "Memphis Tigers", id: "235", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png" },
  'mercer': { name: "Mercer Bears", id: "2382", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2382.png" },
  'mer': { name: "Mercer Bears", id: "2382", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2382.png" },
  'mercyhurst': { name: "Mercyhurst Lakers", id: "2385", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2385.png" },
  'merc': { name: "Mercyhurst Lakers", id: "2385", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2385.png" },
  'merrimack': { name: "Merrimack Warriors", id: "2771", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2771.png" },
  'mrmk': { name: "Merrimack Warriors", id: "2771", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2771.png" },
  'miamioh': { name: "Miami (OH) RedHawks", id: "193", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/193.png" },
  'm-oh': { name: "Miami (OH) RedHawks", id: "193", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/193.png" },
  'miami': { name: "Miami Hurricanes", id: "2390", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png" },
  'mia': { name: "Miami Hurricanes", id: "2390", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png" },
  'michiganst': { name: "Michigan State Spartans", id: "127", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png" },
  'msu': { name: "Michigan State Spartans", id: "127", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png" },
  'michigan': { name: "Michigan Wolverines", id: "130", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/130.png" },
  'mich': { name: "Michigan Wolverines", id: "130", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/130.png" },
  'mtsu': { name: "Middle Tennessee Blue Raiders", id: "2393", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png" },
  'milwaukee': { name: "Milwaukee Panthers", id: "270", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/270.png" },
  'milw': { name: "Milwaukee Panthers", id: "270", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/270.png" },
  'minnesota': { name: "Minnesota Golden Gophers", id: "135", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png" },
  'minn': { name: "Minnesota Golden Gophers", id: "135", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png" },
  'mississippist': { name: "Mississippi State Bulldogs", id: "344", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png" },
  'msst': { name: "Mississippi State Bulldogs", id: "344", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png" },
  'missvalleyst': { name: "Mississippi Valley State Delta Devils", id: "2400", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2400.png" },
  'mvsu': { name: "Mississippi Valley State Delta Devils", id: "2400", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2400.png" },
  'missourist': { name: "Missouri State Bears", id: "2623", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png" },
  'most': { name: "Missouri State Bears", id: "2623", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png" },
  'missouri': { name: "Missouri Tigers", id: "142", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png" },
  'miz': { name: "Missouri Tigers", id: "142", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png" },
  'monmouth': { name: "Monmouth Hawks", id: "2405", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2405.png" },
  'monm': { name: "Monmouth Hawks", id: "2405", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2405.png" },
  'montana': { name: "Montana Grizzlies", id: "149", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/149.png" },
  'mont': { name: "Montana Grizzlies", id: "149", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/149.png" },
  'montanast': { name: "Montana State Bobcats", id: "147", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/147.png" },
  'mtst': { name: "Montana State Bobcats", id: "147", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/147.png" },
  'moreheadst': { name: "Morehead State Eagles", id: "2413", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2413.png" },
  'more': { name: "Morehead State Eagles", id: "2413", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2413.png" },
  'morganst': { name: "Morgan State Bears", id: "2415", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png" },
  'morg': { name: "Morgan State Bears", id: "2415", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png" },
  'mountstmarys': { name: "Mount St. Mary's Mountaineers", id: "116", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/116.png" },
  'msm': { name: "Mount St. Mary's Mountaineers", id: "116", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/116.png" },
  'murrayst': { name: "Murray State Racers", id: "93", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/93.png" },
  'mur': { name: "Murray State Racers", id: "93", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/93.png" },
  'ncstate': { name: "NC State Wolfpack", id: "152", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png" },
  'ncsu': { name: "NC State Wolfpack", id: "152", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png" },
  'njit': { name: "NJIT Highlanders", id: "2885", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2885.png" },
  'navy': { name: "Navy Midshipmen", id: "2426", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png" },
  'nebraska': { name: "Nebraska Cornhuskers", id: "158", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png" },
  'neb': { name: "Nebraska Cornhuskers", id: "158", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png" },
  'nevada': { name: "Nevada Wolf Pack", id: "2440", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png" },
  'nev': { name: "Nevada Wolf Pack", id: "2440", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png" },
  'newhampshire': { name: "New Hampshire Wildcats", id: "160", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/160.png" },
  'unh': { name: "New Hampshire Wildcats", id: "160", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/160.png" },
  'newhaven': { name: "New Haven Chargers", id: "2441", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2441.png" },
  'nhvn': { name: "New Haven Chargers", id: "2441", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2441.png" },
  'newmexico': { name: "New Mexico Lobos", id: "167", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png" },
  'unm': { name: "New Mexico Lobos", id: "167", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png" },
  'newmexicost': { name: "New Mexico State Aggies", id: "166", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/166.png" },
  'nmsu': { name: "New Mexico State Aggies", id: "166", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/166.png" },
  'neworleans': { name: "New Orleans Privateers", id: "2443", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2443.png" },
  'uno': { name: "New Orleans Privateers", id: "2443", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2443.png" },
  'niagara': { name: "Niagara Purple Eagles", id: "315", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/315.png" },
  'nia': { name: "Niagara Purple Eagles", id: "315", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/315.png" },
  'nicholls': { name: "Nicholls Colonels", id: "2447", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png" },
  'nich': { name: "Nicholls Colonels", id: "2447", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png" },
  'norfolkst': { name: "Norfolk State Spartans", id: "2450", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2450.png" },
  'norf': { name: "Norfolk State Spartans", id: "2450", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2450.png" },
  'northalabama': { name: "North Alabama Lions", id: "2453", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2453.png" },
  'una': { name: "North Alabama Lions", id: "2453", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2453.png" },
  'ncat': { name: "North Carolina A&T Aggies", id: "2448", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2448.png" },
  'nccentral': { name: "North Carolina Central Eagles", id: "2428", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png" },
  'nccu': { name: "North Carolina Central Eagles", id: "2428", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png" },
  'northcarolina': { name: "North Carolina Tar Heels", id: "153", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png" },
  'unc': { name: "North Carolina Tar Heels", id: "153", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png" },
  'northdakota': { name: "North Dakota Fighting Hawks", id: "155", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/155.png" },
  'und': { name: "North Dakota Fighting Hawks", id: "155", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/155.png" },
  'ndakotast': { name: "North Dakota State Bison", id: "2449", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png" },
  'ndsu': { name: "North Dakota State Bison", id: "2449", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png" },
  'northflorida': { name: "North Florida Ospreys", id: "2454", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2454.png" },
  'unf': { name: "North Florida Ospreys", id: "2454", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2454.png" },
  'northtexas': { name: "North Texas Mean Green", id: "249", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png" },
  'unt': { name: "North Texas Mean Green", id: "249", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png" },
  'northeastern': { name: "Northeastern Huskies", id: "111", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/111.png" },
  'ne': { name: "Northeastern Huskies", id: "111", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/111.png" },
  'narizona': { name: "Northern Arizona Lumberjacks", id: "2464", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2464.png" },
  'nau': { name: "Northern Arizona Lumberjacks", id: "2464", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2464.png" },
  'ncolorado': { name: "Northern Colorado Bears", id: "2458", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png" },
  'unco': { name: "Northern Colorado Bears", id: "2458", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png" },
  'nillinois': { name: "Northern Illinois Huskies", id: "2459", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png" },
  'niu': { name: "Northern Illinois Huskies", id: "2459", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png" },
  'northerniowa': { name: "Northern Iowa Panthers", id: "2460", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2460.png" },
  'uni': { name: "Northern Iowa Panthers", id: "2460", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2460.png" },
  'nkentucky': { name: "Northern Kentucky Norse", id: "94", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/94.png" },
  'nku': { name: "Northern Kentucky Norse", id: "94", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/94.png" },
  'nwesternst': { name: "Northwestern State Demons", id: "2466", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png" },
  'nwst': { name: "Northwestern State Demons", id: "2466", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png" },
  'northwestern': { name: "Northwestern Wildcats", id: "77", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png" },
  'nu': { name: "Northwestern Wildcats", id: "77", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png" },
  'notredame': { name: "Notre Dame Fighting Irish", id: "87", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png" },
  'nd': { name: "Notre Dame Fighting Irish", id: "87", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png" },
  'oakland': { name: "Oakland Golden Grizzlies", id: "2473", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png" },
  'oak': { name: "Oakland Golden Grizzlies", id: "2473", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png" },
  'ohio': { name: "Ohio Bobcats", id: "195", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/195.png" },
  'ohiostate': { name: "Ohio State Buckeyes", id: "194", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png" },
  'osu': { name: "Ohio State Buckeyes", id: "194", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png" },
  'oklahoma': { name: "Oklahoma Sooners", id: "201", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/201.png" },
  'ou': { name: "Oklahoma Sooners", id: "201", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/201.png" },
  'oklahomast': { name: "Oklahoma State Cowboys", id: "197", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png" },
  'okst': { name: "Oklahoma State Cowboys", id: "197", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png" },
  'olddominion': { name: "Old Dominion Monarchs", id: "295", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png" },
  'odu': { name: "Old Dominion Monarchs", id: "295", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png" },
  'olemiss': { name: "Ole Miss Rebels", id: "145", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/145.png" },
  'miss': { name: "Ole Miss Rebels", id: "145", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/145.png" },
  'omaha': { name: "Omaha Mavericks", id: "2437", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2437.png" },
  'oma': { name: "Omaha Mavericks", id: "2437", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2437.png" },
  'oralroberts': { name: "Oral Roberts Golden Eagles", id: "198", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/198.png" },
  'oru': { name: "Oral Roberts Golden Eagles", id: "198", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/198.png" },
  'oregon': { name: "Oregon Ducks", id: "2483", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png" },
  'ore': { name: "Oregon Ducks", id: "2483", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png" },
  'oregonst': { name: "Oregon State Beavers", id: "204", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png" },
  'orst': { name: "Oregon State Beavers", id: "204", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png" },
  'pacific': { name: "Pacific Tigers", id: "279", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/279.png" },
  'pac': { name: "Pacific Tigers", id: "279", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/279.png" },
  'pennstate': { name: "Penn State Nittany Lions", id: "213", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png" },
  'psu': { name: "Penn State Nittany Lions", id: "213", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png" },
  'penn': { name: "Pennsylvania Quakers", id: "219", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/219.png" },
  'pepperdine': { name: "Pepperdine Waves", id: "2492", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2492.png" },
  'pepp': { name: "Pepperdine Waves", id: "2492", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2492.png" },
  'pitt': { name: "Pittsburgh Panthers", id: "221", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png" },
  'portland': { name: "Portland Pilots", id: "2501", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2501.png" },
  'port': { name: "Portland Pilots", id: "2501", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2501.png" },
  'portlandst': { name: "Portland State Vikings", id: "2502", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png" },
  'prst': { name: "Portland State Vikings", id: "2502", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png" },
  'prairieview': { name: "Prairie View A&M Panthers", id: "2504", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2504.png" },
  'pv': { name: "Prairie View A&M Panthers", id: "2504", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2504.png" },
  'presbyterian': { name: "Presbyterian Blue Hose", id: "2506", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2506.png" },
  'pres': { name: "Presbyterian Blue Hose", id: "2506", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2506.png" },
  'princeton': { name: "Princeton Tigers", id: "163", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png" },
  'prin': { name: "Princeton Tigers", id: "163", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png" },
  'providence': { name: "Providence Friars", id: "2507", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png" },
  'prov': { name: "Providence Friars", id: "2507", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png" },
  'purdue': { name: "Purdue Boilermakers", id: "2509", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png" },
  'pur': { name: "Purdue Boilermakers", id: "2509", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png" },
  'purduefw': { name: "Purdue Fort Wayne Mastodons", id: "2870", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2870.png" },
  'pfw': { name: "Purdue Fort Wayne Mastodons", id: "2870", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2870.png" },
  'quinnipiac': { name: "Quinnipiac Bobcats", id: "2514", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2514.png" },
  'quin': { name: "Quinnipiac Bobcats", id: "2514", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2514.png" },
  'radford': { name: "Radford Highlanders", id: "2515", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2515.png" },
  'rad': { name: "Radford Highlanders", id: "2515", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2515.png" },
  'rhodeisland': { name: "Rhode Island Rams", id: "227", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/227.png" },
  'uri': { name: "Rhode Island Rams", id: "227", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/227.png" },
  'rice': { name: "Rice Owls", id: "242", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/242.png" },
  'richmond': { name: "Richmond Spiders", id: "257", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/257.png" },
  'rich': { name: "Richmond Spiders", id: "257", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/257.png" },
  'rider': { name: "Rider Broncs", id: "2520", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2520.png" },
  'rid': { name: "Rider Broncs", id: "2520", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2520.png" },
  'robertmorris': { name: "Robert Morris Colonials", id: "2523", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2523.png" },
  'rmu': { name: "Robert Morris Colonials", id: "2523", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2523.png" },
  'rutgers': { name: "Rutgers Scarlet Knights", id: "164", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png" },
  'rutg': { name: "Rutgers Scarlet Knights", id: "164", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png" },
  'selouisiana': { name: "SE Louisiana Lions", id: "2545", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2545.png" },
  'sela': { name: "SE Louisiana Lions", id: "2545", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2545.png" },
  'siue': { name: "SIU Edwardsville Cougars", id: "2565", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2565.png" },
  'smu': { name: "SMU Mustangs", id: "2567", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png" },
  'sacramentost': { name: "Sacramento State Hornets", id: "16", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/16.png" },
  'sac': { name: "Sacramento State Hornets", id: "16", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/16.png" },
  'sacredheart': { name: "Sacred Heart Pioneers", id: "2529", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2529.png" },
  'shu': { name: "Sacred Heart Pioneers", id: "2529", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2529.png" },
  'saintfrancis': { name: "Saint Francis Red Flash", id: "2598", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2598.png" },
  'sfpa': { name: "Saint Francis Red Flash", id: "2598", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2598.png" },
  'saintjosephs': { name: "Saint Joseph's Hawks", id: "2603", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2603.png" },
  'joes': { name: "Saint Joseph's Hawks", id: "2603", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2603.png" },
  'saintlouis': { name: "Saint Louis Billikens", id: "139", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/139.png" },
  'slu': { name: "Saint Louis Billikens", id: "139", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/139.png" },
  'saintmarys': { name: "Saint Mary's Gaels", id: "2608", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png" },
  'smc': { name: "Saint Mary's Gaels", id: "2608", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png" },
  'saintpeters': { name: "Saint Peter's Peacocks", id: "2612", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2612.png" },
  'spu': { name: "Saint Peter's Peacocks", id: "2612", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2612.png" },
  'samhouston': { name: "Sam Houston Bearkats", id: "2534", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png" },
  'shsu': { name: "Sam Houston Bearkats", id: "2534", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png" },
  'samford': { name: "Samford Bulldogs", id: "2535", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2535.png" },
  'sam': { name: "Samford Bulldogs", id: "2535", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2535.png" },
  'sandiegost': { name: "San Diego State Aztecs", id: "21", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png" },
  'sdsu': { name: "San Diego State Aztecs", id: "21", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png" },
  'sandiego': { name: "San Diego Toreros", id: "301", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/301.png" },
  'usd': { name: "San Diego Toreros", id: "301", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/301.png" },
  'sanfrancisco': { name: "San Francisco Dons", id: "2539", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png" },
  'sf': { name: "San Francisco Dons", id: "2539", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png" },
  'sanjosst': { name: "San José State Spartans", id: "23", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/23.png" },
  'sjsu': { name: "San José State Spartans", id: "23", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/23.png" },
  'santaclara': { name: "Santa Clara Broncos", id: "2541", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2541.png" },
  'scu': { name: "Santa Clara Broncos", id: "2541", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2541.png" },
  'seattleu': { name: "Seattle U Redhawks", id: "2547", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2547.png" },
  'sea': { name: "Seattle U Redhawks", id: "2547", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2547.png" },
  'setonhall': { name: "Seton Hall Pirates", id: "2550", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png" },
  'hall': { name: "Seton Hall Pirates", id: "2550", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png" },
  'siena': { name: "Siena Saints", id: "2561", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2561.png" },
  'sie': { name: "Siena Saints", id: "2561", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2561.png" },
  'southalabama': { name: "South Alabama Jaguars", id: "6", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/6.png" },
  'usa': { name: "South Alabama Jaguars", id: "6", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/6.png" },
  'southcarolina': { name: "South Carolina Gamecocks", id: "2579", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png" },
  'sc': { name: "South Carolina Gamecocks", id: "2579", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png" },
  'scstate': { name: "South Carolina State Bulldogs", id: "2569", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2569.png" },
  'scst': { name: "South Carolina State Bulldogs", id: "2569", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2569.png" },
  'scupstate': { name: "South Carolina Upstate Spartans", id: "2908", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2908.png" },
  'upst': { name: "South Carolina Upstate Spartans", id: "2908", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2908.png" },
  'southdakota': { name: "South Dakota Coyotes", id: "233", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/233.png" },
  'sdak': { name: "South Dakota Coyotes", id: "233", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/233.png" },
  'sdakotast': { name: "South Dakota State Jackrabbits", id: "2571", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png" },
  'sdst': { name: "South Dakota State Jackrabbits", id: "2571", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png" },
  'southflorida': { name: "South Florida Bulls", id: "58", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png" },
  'usf': { name: "South Florida Bulls", id: "58", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png" },
  'semissouri': { name: "Southeast Missouri State Redhawks", id: "2546", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png" },
  'semo': { name: "Southeast Missouri State Redhawks", id: "2546", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png" },
  'sillinois': { name: "Southern Illinois Salukis", id: "79", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/79.png" },
  'siu': { name: "Southern Illinois Salukis", id: "79", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/79.png" },
  'southern': { name: "Southern Jaguars", id: "2582", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2582.png" },
  'sou': { name: "Southern Jaguars", id: "2582", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2582.png" },
  'southernmiss': { name: "Southern Miss Golden Eagles", id: "2572", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png" },
  'usm': { name: "Southern Miss Golden Eagles", id: "2572", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png" },
  'southernutah': { name: "Southern Utah Thunderbirds", id: "253", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/253.png" },
  'suu': { name: "Southern Utah Thunderbirds", id: "253", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/253.png" },
  'stbonaventure': { name: "St. Bonaventure Bonnies", id: "179", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/179.png" },
  'sbu': { name: "St. Bonaventure Bonnies", id: "179", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/179.png" },
  'stjohns': { name: "St. John's Red Storm", id: "2599", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png" },
  'sju': { name: "St. John's Red Storm", id: "2599", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png" },
  'stthomasmn': { name: "St. Thomas-Minnesota Tommies", id: "2900", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2900.png" },
  'stmn': { name: "St. Thomas-Minnesota Tommies", id: "2900", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2900.png" },
  'stanford': { name: "Stanford Cardinal", id: "24", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png" },
  'stan': { name: "Stanford Cardinal", id: "24", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png" },
  'sfaustin': { name: "Stephen F. Austin Lumberjacks", id: "2617", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png" },
  'sfa': { name: "Stephen F. Austin Lumberjacks", id: "2617", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png" },
  'stetson': { name: "Stetson Hatters", id: "56", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/56.png" },
  'stet': { name: "Stetson Hatters", id: "56", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/56.png" },
  'stonehill': { name: "Stonehill Skyhawks", id: "284", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/284.png" },
  'sto': { name: "Stonehill Skyhawks", id: "284", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/284.png" },
  'stonybrook': { name: "Stony Brook Seawolves", id: "2619", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2619.png" },
  'stbk': { name: "Stony Brook Seawolves", id: "2619", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2619.png" },
  'syracuse': { name: "Syracuse Orange", id: "183", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png" },
  'syr': { name: "Syracuse Orange", id: "183", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png" },
  'tcu': { name: "TCU Horned Frogs", id: "2628", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png" },
  'tarletonst': { name: "Tarleton State Texans", id: "2627", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2627.png" },
  'tar': { name: "Tarleton State Texans", id: "2627", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2627.png" },
  'temple': { name: "Temple Owls", id: "218", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png" },
  'tem': { name: "Temple Owls", id: "218", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png" },
  'tennesseest': { name: "Tennessee State Tigers", id: "2634", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2634.png" },
  'tnst': { name: "Tennessee State Tigers", id: "2634", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2634.png" },
  'tennesseetech': { name: "Tennessee Tech Golden Eagles", id: "2635", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2635.png" },
  'tntc': { name: "Tennessee Tech Golden Eagles", id: "2635", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2635.png" },
  'tennessee': { name: "Tennessee Volunteers", id: "2633", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png" },
  'tenn': { name: "Tennessee Volunteers", id: "2633", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png" },
  'texasam': { name: "Texas A&M Aggies", id: "245", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png" },
  'ta&m': { name: "Texas A&M Aggies", id: "245", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png" },
  'texasamcc': { name: "Texas A&M-Corpus Christi Islanders", id: "357", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/357.png" },
  'amcc': { name: "Texas A&M-Corpus Christi Islanders", id: "357", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/357.png" },
  'texas': { name: "Texas Longhorns", id: "251", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png" },
  'tex': { name: "Texas Longhorns", id: "251", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png" },
  'texassouthern': { name: "Texas Southern Tigers", id: "2640", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png" },
  'txso': { name: "Texas Southern Tigers", id: "2640", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png" },
  'texasst': { name: "Texas State Bobcats", id: "326", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png" },
  'txst': { name: "Texas State Bobcats", id: "326", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png" },
  'texastech': { name: "Texas Tech Red Raiders", id: "2641", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png" },
  'ttu': { name: "Texas Tech Red Raiders", id: "2641", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png" },
  'thecitadel': { name: "The Citadel Bulldogs", id: "2643", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2643.png" },
  'cit': { name: "The Citadel Bulldogs", id: "2643", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2643.png" },
  'toledo': { name: "Toledo Rockets", id: "2649", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png" },
  'tol': { name: "Toledo Rockets", id: "2649", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png" },
  'towson': { name: "Towson Tigers", id: "119", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/119.png" },
  'tow': { name: "Towson Tigers", id: "119", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/119.png" },
  'troy': { name: "Troy Trojans", id: "2653", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png" },
  'tulane': { name: "Tulane Green Wave", id: "2655", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png" },
  'tuln': { name: "Tulane Green Wave", id: "2655", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png" },
  'tulsa': { name: "Tulsa Golden Hurricane", id: "202", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png" },
  'tlsa': { name: "Tulsa Golden Hurricane", id: "202", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png" },
  'uab': { name: "UAB Blazers", id: "5", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/5.png" },
  'ualbany': { name: "UAlbany Great Danes", id: "399", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png" },
  'ualb': { name: "UAlbany Great Danes", id: "399", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png" },
  'ucdavis': { name: "UC Davis Aggies", id: "302", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/302.png" },
  'ucd': { name: "UC Davis Aggies", id: "302", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/302.png" },
  'ucirvine': { name: "UC Irvine Anteaters", id: "300", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/300.png" },
  'uci': { name: "UC Irvine Anteaters", id: "300", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/300.png" },
  'ucriverside': { name: "UC Riverside Highlanders", id: "27", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/27.png" },
  'ucr': { name: "UC Riverside Highlanders", id: "27", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/27.png" },
  'ucsandiego': { name: "UC San Diego Tritons", id: "28", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/28.png" },
  'ucsd': { name: "UC San Diego Tritons", id: "28", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/28.png" },
  'santabarbara': { name: "UC Santa Barbara Gauchos", id: "2540", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2540.png" },
  'ucsb': { name: "UC Santa Barbara Gauchos", id: "2540", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2540.png" },
  'ucf': { name: "UCF Knights", id: "2116", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png" },
  'ucla': { name: "UCLA Bruins", id: "26", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png" },
  'uconn': { name: "UConn Huskies", id: "41", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png" },
  'conn': { name: "UConn Huskies", id: "41", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png" },
  'uic': { name: "UIC Flames", id: "82", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/82.png" },
  'ulmonroe': { name: "UL Monroe Warhawks", id: "2433", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png" },
  'ulm': { name: "UL Monroe Warhawks", id: "2433", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png" },
  'umbc': { name: "UMBC Retrievers", id: "2378", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2378.png" },
  'umasslowell': { name: "UMass Lowell River Hawks", id: "2349", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2349.png" },
  'uml': { name: "UMass Lowell River Hawks", id: "2349", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2349.png" },
  'uncasheville': { name: "UNC Asheville Bulldogs", id: "2427", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2427.png" },
  'unca': { name: "UNC Asheville Bulldogs", id: "2427", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2427.png" },
  'uncgreensboro': { name: "UNC Greensboro Spartans", id: "2430", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png" },
  'uncg': { name: "UNC Greensboro Spartans", id: "2430", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png" },
  'uncwilmington': { name: "UNC Wilmington Seahawks", id: "350", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/350.png" },
  'uncw': { name: "UNC Wilmington Seahawks", id: "350", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/350.png" },
  'unlv': { name: "UNLV Rebels", id: "2439", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png" },
  'usc': { name: "USC Trojans", id: "30", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png" },
  'utarlington': { name: "UT Arlington Mavericks", id: "250", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/250.png" },
  'uta': { name: "UT Arlington Mavericks", id: "250", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/250.png" },
  'utmartin': { name: "UT Martin Skyhawks", id: "2630", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2630.png" },
  'utm': { name: "UT Martin Skyhawks", id: "2630", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2630.png" },
  'utriogrande': { name: "UT Rio Grande Valley Vaqueros", id: "292", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/292.png" },
  'rgv': { name: "UT Rio Grande Valley Vaqueros", id: "292", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/292.png" },
  'utep': { name: "UTEP Miners", id: "2638", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png" },
  'utsa': { name: "UTSA Roadrunners", id: "2636", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png" },
  'utahstate': { name: "Utah State Aggies", id: "328", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png" },
  'usu': { name: "Utah State Aggies", id: "328", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png" },
  'utahtech': { name: "Utah Tech Trailblazers", id: "3101", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/3101.png" },
  'utu': { name: "Utah Tech Trailblazers", id: "3101", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/3101.png" },
  'utah': { name: "Utah Utes", id: "254", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/254.png" },
  'utahvalley': { name: "Utah Valley Wolverines", id: "3084", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/3084.png" },
  'uvu': { name: "Utah Valley Wolverines", id: "3084", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/3084.png" },
  'vcu': { name: "VCU Rams", id: "2670", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png" },
  'vmi': { name: "VMI Keydets", id: "2678", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2678.png" },
  'valparaiso': { name: "Valparaiso Beacons", id: "2674", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2674.png" },
  'val': { name: "Valparaiso Beacons", id: "2674", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2674.png" },
  'vanderbilt': { name: "Vanderbilt Commodores", id: "238", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png" },
  'van': { name: "Vanderbilt Commodores", id: "238", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png" },
  'vermont': { name: "Vermont Catamounts", id: "261", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/261.png" },
  'uvm': { name: "Vermont Catamounts", id: "261", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/261.png" },
  'villanova': { name: "Villanova Wildcats", id: "222", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/222.png" },
  'vill': { name: "Villanova Wildcats", id: "222", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/222.png" },
  'virginia': { name: "Virginia Cavaliers", id: "258", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png" },
  'uva': { name: "Virginia Cavaliers", id: "258", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png" },
  'virginiatech': { name: "Virginia Tech Hokies", id: "259", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png" },
  'vt': { name: "Virginia Tech Hokies", id: "259", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png" },
  'wagner': { name: "Wagner Seahawks", id: "2681", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2681.png" },
  'wag': { name: "Wagner Seahawks", id: "2681", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2681.png" },
  'wakeforest': { name: "Wake Forest Demon Deacons", id: "154", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png" },
  'wake': { name: "Wake Forest Demon Deacons", id: "154", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png" },
  'washington': { name: "Washington Huskies", id: "264", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png" },
  'wash': { name: "Washington Huskies", id: "264", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png" },
  'washingtonst': { name: "Washington State Cougars", id: "265", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png" },
  'wsu': { name: "Washington State Cougars", id: "265", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png" },
  'weberst': { name: "Weber State Wildcats", id: "2692", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png" },
  'web': { name: "Weber State Wildcats", id: "2692", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png" },
  'westgeorgia': { name: "West Georgia Wolves", id: "2698", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2698.png" },
  'wga': { name: "West Georgia Wolves", id: "2698", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2698.png" },
  'westvirginia': { name: "West Virginia Mountaineers", id: "277", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png" },
  'wvu': { name: "West Virginia Mountaineers", id: "277", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png" },
  'wcarolina': { name: "Western Carolina Catamounts", id: "2717", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2717.png" },
  'wcu': { name: "Western Carolina Catamounts", id: "2717", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2717.png" },
  'willinois': { name: "Western Illinois Leathernecks", id: "2710", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2710.png" },
  'wiu': { name: "Western Illinois Leathernecks", id: "2710", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2710.png" },
  'westernky': { name: "Western Kentucky Hilltoppers", id: "98", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png" },
  'wku': { name: "Western Kentucky Hilltoppers", id: "98", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png" },
  'wmichigan': { name: "Western Michigan Broncos", id: "2711", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png" },
  'wmu': { name: "Western Michigan Broncos", id: "2711", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png" },
  'wichitast': { name: "Wichita State Shockers", id: "2724", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png" },
  'wich': { name: "Wichita State Shockers", id: "2724", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png" },
  'williammary': { name: "William & Mary Tribe", id: "2729", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2729.png" },
  'w&m': { name: "William & Mary Tribe", id: "2729", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2729.png" },
  'winthrop': { name: "Winthrop Eagles", id: "2737", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2737.png" },
  'win': { name: "Winthrop Eagles", id: "2737", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2737.png" },
  'wisconsin': { name: "Wisconsin Badgers", id: "275", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png" },
  'wis': { name: "Wisconsin Badgers", id: "275", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png" },
  'wofford': { name: "Wofford Terriers", id: "2747", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2747.png" },
  'wof': { name: "Wofford Terriers", id: "2747", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2747.png" },
  'wrightst': { name: "Wright State Raiders", id: "2750", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2750.png" },
  'wrst': { name: "Wright State Raiders", id: "2750", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2750.png" },
  'wyoming': { name: "Wyoming Cowboys", id: "2751", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png" },
  'wyo': { name: "Wyoming Cowboys", id: "2751", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png" },
  'xavier': { name: "Xavier Musketeers", id: "2752", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png" },
  'xav': { name: "Xavier Musketeers", id: "2752", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png" },
  'yale': { name: "Yale Bulldogs", id: "43", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/43.png" },
  'youngstownst': { name: "Youngstown State Penguins", id: "2754", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png" },
  'ysu': { name: "Youngstown State Penguins", id: "2754", logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png" },
};

// Helper to find logo from input string (fuzzy match)
export const getTeamLogo = (input: string): string | null => {
  if (!input) return null;
  const lower = input.toLowerCase();

  // 1. Try NFL Direct Key
  if (NFL_TEAMS[lower]) return NFL_TEAMS[lower].logo;

  // 2. Try NCAA Direct Key
  if (NCAA_TEAMS[lower]) return NCAA_TEAMS[lower].logo;

  // 3. Fuzzy Match NFL
  const nflKey = Object.keys(NFL_TEAMS).find(k =>
    NFL_TEAMS[k].name.toLowerCase().includes(lower) ||
    lower.includes(NFL_TEAMS[k].name.toLowerCase()) ||
    NFL_TEAMS[k].abbr.toLowerCase() === lower
  );
  if (nflKey) return NFL_TEAMS[nflKey].logo;

  // 4. Fuzzy Match NCAA
  // Remove seed prefixes like "E1-", "W2-" for better matching
  const cleanName = lower.replace(/^[ewsm][0-9]{1,2}-/, '').replace(/-/g, ' ');

  const ncaaKey = Object.keys(NCAA_TEAMS).find(k =>
    NCAA_TEAMS[k].name.toLowerCase().includes(cleanName) ||
    cleanName.includes(NCAA_TEAMS[k].name.toLowerCase())
  );
  if (ncaaKey) return NCAA_TEAMS[ncaaKey].logo;

  return null;
};
